export const FETCH_DEVICES = 'FETCH_DEVICES';
export const FETCH_FILE_PATHS = 'FETCH_FILE_PATHS';

export const REQUEST_FILE_PATHS = 'REQUEST_FILE_PATHS';
export const FETCH_UPLOADED_FILE_PATHS = 'FETCH_UPLOADED_FILE_PATHS';
export const REQUEST_FILE = 'REQUEST_FILE_PATHS';

export const UPDATE_FILES_TREE = 'UPDATE_FILES_TREE';

